version: "3.7"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  django_migrations:
    build: .
    command: python manage.py migrate
    depends_on:
      - db
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - SECRET_KEY=secret
      - DJANGO_ALLOWED_HOSTS=django 0.0.0.0 [::1]
    depends_on:
      - django_migrations
